### ISSUE TITLE
🚀 [FEAT] 박사과정 학생을 위한 연구실적 등록 시스템 개발

### ISSUE THREAD

**Issue by hynseok** [SystemConsultantGroup/ICC-grad-dissertion-manage-backend#147]
### Describe Existing Problem ❓

박사과정 학생은 학생 등록시 심사위원 없이 지도교수만 입력하여도 등록이 되어야 합니다.
박사과정 학생은 본 사이트에서 연구실적만 등록합니다.

### Describe Solution 💸

논의 필요

### CheckList ✔️

- [X] 관련 Issue 가 이미 존재하는 지 확인해보셨나요?

**Comment by yesjuhee** [comment]
작업 목록
- [ ] user DB 구조 수정
- [ ] 박사과정생 학생 등록 기능 추가
- [ ] 박사과정생 엑셀 등록 기능 추가
